[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18" # Optional, specify Node.js version if needed

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
